"use client";

import { useEffect, useRef, useState } from "react";

type Tab = "menu" | "wishlist" | "shopping" | "cook" | "inventory" | "stats";
type Dish = { id:string; name:string; desc:string; emoji:string; tone:string; minutes:number; calories:number; protein:number; tags:string[]; cost:number; ingredients:{name:string;qty:string;category:string}[]; steps:string[] };
type InventoryItem = { id:string; name:string; amount:string; category:string; daysLeft:number; icon:string };
type KitchenState = { ordered:string[]; wishlist:string[]; confirmed:boolean; checkedShopping:string[]; completedSteps:string[]; inventory:InventoryItem[] };

const dishes: Dish[] = [
  { id:"tomato-egg",name:"番茄炒蛋",desc:"酸甜下饭 · 家庭常驻",emoji:"🍅",tone:"sunset",minutes:18,calories:320,protein:18,tags:["快手","下饭"],cost:6.4,ingredients:[{name:"番茄",qty:"3 个",category:"蔬菜"},{name:"鸡蛋",qty:"4 个",category:"蛋奶"},{name:"小葱",qty:"2 根",category:"蔬菜"}],steps:["番茄切滚刀块，小葱切末，鸡蛋加一小撮盐打散","热锅下油，鸡蛋炒至八成熟后盛出","原锅炒番茄，加盐和少许糖，炒出汁","鸡蛋回锅翻匀 30 秒，撒葱花出锅"] },
  { id:"beef",name:"黑椒牛肉",desc:"嫩滑多汁 · 彩椒爽脆",emoji:"🥩",tone:"pepper",minutes:28,calories:460,protein:35,tags:["高蛋白","人气"],cost:14.8,ingredients:[{name:"牛里脊",qty:"300 g",category:"肉类"},{name:"彩椒",qty:"2 个",category:"蔬菜"},{name:"洋葱",qty:"半个",category:"蔬菜"}],steps:["牛肉逆纹切片，加生抽、淀粉和油抓匀腌 10 分钟","彩椒与洋葱切块，调好黑椒汁","大火滑炒牛肉至变色，立即盛出","炒香洋葱和彩椒，牛肉回锅淋汁翻匀"] },
  { id:"salmon",name:"香煎三文鱼",desc:"柠檬黄油 · 外脆里嫩",emoji:"🐟",tone:"salmon",minutes:25,calories:510,protein:39,tags:["高蛋白","清淡"],cost:16.5,ingredients:[{name:"三文鱼",qty:"2 块",category:"海鲜"},{name:"柠檬",qty:"1 个",category:"水果"},{name:"芦笋",qty:"1 把",category:"蔬菜"}],steps:["三文鱼擦干，撒盐和黑胡椒静置 8 分钟","锅烧热后皮面朝下，中火煎 4 分钟","翻面煎 2–3 分钟，加入黄油和蒜瓣淋油","静置 2 分钟，挤柠檬汁，与芦笋装盘"] },
  { id:"tofu",name:"家常豆腐煲",desc:"暖呼呼 · 一锅就够",emoji:"🥘",tone:"tofu",minutes:32,calories:390,protein:22,tags:["暖胃","素食"],cost:8.2,ingredients:[{name:"嫩豆腐",qty:"1 盒",category:"豆制品"},{name:"香菇",qty:"6 朵",category:"蔬菜"},{name:"青菜",qty:"1 把",category:"蔬菜"}],steps:["豆腐切块，香菇切片，青菜洗净","豆腐两面煎至微黄后盛出","炒香蒜末和香菇，加高汤与豆腐焖 8 分钟","放青菜，水淀粉薄勾芡后关火"] },
  { id:"chicken",name:"葱油鸡腿",desc:"葱香浓郁 · 鲜嫩多汁",emoji:"🍗",tone:"chicken",minutes:35,calories:540,protein:42,tags:["高蛋白","下饭"],cost:10.6,ingredients:[{name:"去骨鸡腿",qty:"3 块",category:"肉类"},{name:"小葱",qty:"1 把",category:"蔬菜"},{name:"姜",qty:"1 块",category:"调味"}],steps:["鸡腿擦干，加盐腌 10 分钟","鸡皮朝下小火煎出油脂，翻面煎熟","鸡腿静置后切块装盘","葱姜末淋热油，加生抽调匀后浇在鸡肉上"] },
  { id:"shrimp",name:"蒜香西兰花虾仁",desc:"清爽鲜甜 · 工作日晚餐",emoji:"🍤",tone:"garden",minutes:20,calories:350,protein:31,tags:["清淡","快手"],cost:12.3,ingredients:[{name:"虾仁",qty:"300 g",category:"海鲜"},{name:"西兰花",qty:"1 颗",category:"蔬菜"},{name:"蒜",qty:"4 瓣",category:"调味"}],steps:["虾仁擦干，加盐和黑胡椒腌 5 分钟","西兰花焯水 60 秒，捞出沥干","热锅炒香蒜末，虾仁炒至变色","加入西兰花和少许蚝油，大火翻匀出锅"] },
];

const initialState:KitchenState={ordered:[],wishlist:["salmon"],confirmed:false,checkedShopping:[],completedSteps:[],inventory:[{id:"rice",name:"大米",amount:"1.8 kg",category:"主食",daysLeft:90,icon:"🍚"},{id:"eggs",name:"鸡蛋",amount:"8 个",category:"蛋奶",daysLeft:12,icon:"🥚"},{id:"spinach",name:"菠菜",amount:"1 把",category:"蔬菜",daysLeft:2,icon:"🥬"},{id:"garlic",name:"蒜",amount:"2 头",category:"调味",daysLeft:24,icon:"🧄"}]};
const nav:[Tab,string,string][]=[["menu","⌂","今日菜单"],["wishlist","♡","想吃清单"],["shopping","🧺","买菜清单"],["cook","♨","做饭 SOP"],["inventory","◫","厨房库存"],["stats","⌁","本月数据"]];
const filters=["全部","30分钟内","高蛋白","清淡","下饭"];

export default function Home(){
  const [tab,setTab]=useState<Tab>("menu"); const [filter,setFilter]=useState("全部"); const [role,setRole]=useState<"wife"|"cook">("wife"); const [state,setState]=useState<KitchenState>(initialState); const [ready,setReady]=useState(false); const [saved,setSaved]=useState(true); const [storageReady,setStorageReady]=useState(true); const skipFirst=useRef(true);
  useEffect(()=>{fetch("/api/state").then(async r=>{const data=await r.json();if(data.state)setState(data.state);setStorageReady(!data.warning);setReady(true)}).catch(()=>{setStorageReady(false);setReady(true)})},[]);
  useEffect(()=>{if(!ready||skipFirst.current){skipFirst.current=false;return}setSaved(false);const timer=setTimeout(()=>fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(state)}).then(r=>{if(!r.ok)throw new Error("save failed");setStorageReady(true);setSaved(true)}).catch(()=>{setStorageReady(false);setSaved(false)}),450);return()=>clearTimeout(timer)},[state,ready]);
  const chosen=state.ordered.map(id=>dishes.find(d=>d.id===id)).filter(Boolean) as Dish[];
  const wanted=state.wishlist.map(id=>dishes.find(d=>d.id===id)).filter(Boolean) as Dish[];
  const shopping=(()=>{const inventoryNames=new Set(state.inventory.map(i=>i.name));const map=new Map<string,{name:string;qty:string;category:string;forDish:string[]}>();chosen.forEach(d=>d.ingredients.forEach(item=>{if(inventoryNames.has(item.name))return;const current=map.get(item.name);if(current)current.forDish.push(d.name);else map.set(item.name,{...item,forDish:[d.name]})}));return [...map.values()]})();
  const visible=dishes.filter(d=>filter==="全部"?true:filter==="30分钟内"?d.minutes<=30:d.tags.includes(filter));
  const update=(patch:Partial<KitchenState>)=>setState(current=>({...current,...patch}));
  const toggle=(key:"ordered"|"wishlist"|"checkedShopping"|"completedSteps",id:string)=>update({[key]:state[key].includes(id)?state[key].filter(item=>item!==id):[...state[key],id]});
  const confirmOrder=()=>{update({confirmed:true,checkedShopping:[],completedSteps:[]});setRole("cook");setTab("shopping")};
  const title={menu:"晚上想吃什么？",wishlist:"最近想吃这些",shopping:"今晚要买什么？",cook:"开火，按顺序来",inventory:"家里还有什么？",stats:"这个月吃得怎么样？"}[tab];

  return <main className="app-shell">
    <header className="topbar"><button className="brand plain" onClick={()=>setTab("menu")}><span className="brand-mark">灶</span><span><b>今晚吃什么</b><small>我们的家庭厨房</small></span></button><div className="top-actions"><span className={saved&&storageReady?"save-state":"save-state saving"}>{!ready?"○ 连接中":!storageReady?"○ 数据库未连接":saved?"● 已同步":"○ 保存中"}</span><button className="role-pill" onClick={()=>setRole(role==="wife"?"cook":"wife")}>{role==="wife"?"♡ 老婆点菜中":"♨ 掌勺模式"}</button><button className="avatar" onClick={()=>setRole(role==="wife"?"cook":"wife")} aria-label="切换角色">{role==="wife"?"她":"我"}</button></div></header>
    <div className="page-grid"><aside className="sidebar"><nav>{nav.map(([id,icon,label])=><button key={id} className={tab===id?"nav-item active":"nav-item"} onClick={()=>setTab(id)}><span>{icon}</span>{label}{id==="wishlist"&&<em>{state.wishlist.length}</em>}{id==="shopping"&&<em>{shopping.length}</em>}</button>)}<div className="nav-divider"/></nav><div className="fridge-note"><span>🧊</span><div><b>冰箱小提醒</b><p>菠菜还有 2 天到期</p></div></div></aside>
      <section className="content">
        <div className="welcome-row"><div><p className="eyebrow">OUR HOME · TODAY</p><h1>{title}</h1><p className="lede">{tab==="menu"?"今天你只管点，剩下的交给我。":tab==="cook"?"备菜、开火、出锅，一个步骤都不乱。":"点菜、库存和预算，全部自动串起来。"}</p></div>{tab==="menu"&&<div className="weather-card"><span>☀</span><div><b>24°C</b><small>适合吃点清爽的</small></div></div>}</div>

        {tab==="menu"&&<Menu dishes={visible} filter={filter} setFilter={setFilter} state={state} toggle={toggle} confirmOrder={confirmOrder}/>} 
        {tab==="wishlist"&&<Wishlist dishes={wanted} moveToOrder={(id)=>{if(!state.ordered.includes(id))update({ordered:[...state.ordered,id]});}} remove={(id)=>toggle("wishlist",id)}/>} 
        {tab==="shopping"&&<Shopping items={shopping} checked={state.checkedShopping} toggle={(id)=>toggle("checkedShopping",id)} onCook={()=>setTab("cook")} confirmed={state.confirmed}/>} 
        {tab==="cook"&&<Cook chosen={chosen} completed={state.completedSteps} toggle={(id)=>toggle("completedSteps",id)}/>} 
        {tab==="inventory"&&<Inventory items={state.inventory} remove={(id)=>update({inventory:state.inventory.filter(item=>item.id!==id)})} add={(item)=>update({inventory:[...state.inventory,item]})}/>} 
        {tab==="stats"&&<Stats chosen={chosen}/>} 
      </section>
    </div>
    <nav className="mobile-nav">{nav.slice(0,5).map(([id,icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><span>{icon}</span>{label.replace("今日","").replace("清单","")}</button>)}</nav>
  </main>
}

function Menu({dishes,filter,setFilter,state,toggle,confirmOrder}:{dishes:Dish[];filter:string;setFilter:(x:string)=>void;state:KitchenState;toggle:(key:"ordered"|"wishlist",id:string)=>void;confirmOrder:()=>void}){return <><div className="filter-row">{filters.map(item=><button key={item} className={filter===item?"filter active":"filter"} onClick={()=>setFilter(item)}>{item}</button>)}</div>{state.ordered.length>0&&<div className="order-banner"><div><span>✓</span><p><b>今晚已选 {state.ordered.length} 道菜</b><small>{state.ordered.map(id=>dishes.find(d=>d.id===id)?.name??id).join("、")}</small></p></div><button onClick={()=>document.getElementById("summary")?.scrollIntoView({behavior:"smooth"})}>去确认</button></div>}<div className="section-heading"><div><h2>今日推荐</h2><p>按家里库存和你们的口味挑好了</p></div><button className="text-button" onClick={()=>setFilter("全部")}>↻ 换一批</button></div><div className="dish-grid">{dishes.map(d=><DishCard key={d.id} dish={d} ordered={state.ordered.includes(d.id)} wished={state.wishlist.includes(d.id)} onOrder={()=>toggle("ordered",d.id)} onWish={()=>toggle("wishlist",d.id)}/>)}</div><section className="summary-card" id="summary"><div><p className="eyebrow">TONIGHT&apos;S ORDER</p><h2>{state.ordered.length?"今晚菜单已选好":"还没有点菜"}</h2><p>{state.ordered.length?"确认后自动合并食材，生成买菜清单与做饭顺序。":"从上面选一道想吃的菜吧。"}</p></div><div className="summary-dishes">{state.ordered.map(id=><span key={id}>{dishes.find(d=>d.id===id)?.emoji}</span>)}</div><button disabled={!state.ordered.length} onClick={confirmOrder}>{state.ordered.length?"确认今晚菜单 →":"等你点菜"}</button></section></>}
function DishCard({dish,ordered,wished,onOrder,onWish}:{dish:Dish;ordered:boolean;wished:boolean;onOrder:()=>void;onWish:()=>void}){return <article className="dish-card"><div className={`dish-visual ${dish.tone}`}><span className="food-emoji">{dish.emoji}</span><div className="plate"/><button className={wished?"heart active":"heart"} aria-label={wished?`移除${dish.name}`:`收藏${dish.name}`} onClick={onWish}>{wished?"♥":"♡"}</button><span className="time">◷ {dish.minutes} 分钟</span></div><div className="dish-body"><div className="dish-title-row"><div><h3>{dish.name}</h3><p>{dish.desc}</p></div><span className="rating">★ 4.9</span></div><div className="nutrition"><span>{dish.calories} kcal</span><i/><span>蛋白质 {dish.protein}g</span></div><div className="tags">{dish.tags.map(tag=><span key={tag}>{tag}</span>)}</div><button className={ordered?"order-button ordered":"order-button"} onClick={onOrder}>{ordered?"✓ 已点这道":"+ 今晚吃这个"}</button></div></article>}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="empty"><span>{icon}</span><h2>{title}</h2><p>{text}</p></div>}
function Wishlist({dishes,moveToOrder,remove}:{dishes:Dish[];moveToOrder:(id:string)=>void;remove:(id:string)=>void}){return dishes.length?<div className="list-stack top-space">{dishes.map(d=><article className="wish-row" key={d.id}><div className={`mini-visual ${d.tone}`}>{d.emoji}</div><div><h3>{d.name}</h3><p>{d.desc} · {d.minutes} 分钟</p></div><div className="row-actions"><button className="ghost" onClick={()=>remove(d.id)}>移除</button><button className="primary" onClick={()=>moveToOrder(d.id)}>今晚吃</button></div></article>)}</div>:<Empty icon="♡" title="想吃清单还是空的" text="看到喜欢的菜，点一下爱心就会留在这里。"/>}
function Shopping({items,checked,toggle,onCook,confirmed}:{items:{name:string;qty:string;category:string;forDish:string[]}[];checked:string[];toggle:(id:string)=>void;onCook:()=>void;confirmed:boolean}){if(!confirmed)return <Empty icon="🧺" title="先确认今晚菜单" text="确认后，会自动扣除家中库存并合并需要购买的食材。"/>;const done=items.filter(i=>checked.includes(i.name)).length;return <><div className="progress-card top-space"><div><b>{done}/{items.length} 已买</b><span>预计 $ {items.reduce((sum)=>sum+3.8,0).toFixed(2)}</span></div><div className="progress"><i style={{width:`${items.length?done/items.length*100:100}%`}}/></div></div><div className="shopping-grid">{["肉类","海鲜","蔬菜","水果","蛋奶","豆制品","调味"].map(cat=>{const group=items.filter(i=>i.category===cat);return group.length?<section className="shopping-group" key={cat}><h3>{cat}</h3>{group.map(item=><label className={checked.includes(item.name)?"check-row checked":"check-row"} key={item.name}><input type="checkbox" checked={checked.includes(item.name)} onChange={()=>toggle(item.name)}/><span className="fake-check">✓</span><span><b>{item.name}</b><small>{item.forDish.join("、")}</small></span><em>{item.qty}</em></label>)}</section>:null})}</div><button className="wide-action" onClick={onCook}>东西齐了，开始做饭 →</button></>}
function Cook({chosen,completed,toggle}:{chosen:Dish[];completed:string[];toggle:(id:string)=>void}){if(!chosen.length)return <Empty icon="♨" title="今晚还没选菜" text="先去菜单点菜，SOP 会按火候和时间自动排好。"/>;const total=chosen.reduce((s,d)=>s+d.steps.length,0);return <><div className="cook-overview top-space"><div><span>⏱</span><p><b>预计 {Math.max(...chosen.map(d=>d.minutes))+8} 分钟</b><small>{chosen.length} 道菜 · 先备菜，再集中开火</small></p></div><strong>{completed.length}/{total}</strong></div><div className="timeline">{chosen.map((d,dishIndex)=><section className="cook-dish" key={d.id}><div className={`cook-icon ${d.tone}`}>{d.emoji}</div><div className="cook-content"><h2>{d.name}<span>{d.minutes} 分钟</span></h2>{d.steps.map((step,index)=>{const number=chosen.slice(0,dishIndex).reduce((sum,item)=>sum+item.steps.length,0)+index+1;const id=`${d.id}-${index}`;return <label className={completed.includes(id)?"step done":"step"} key={id}><input type="checkbox" checked={completed.includes(id)} onChange={()=>toggle(id)}/><span>{number}</span><p>{step}</p></label>})}</div></section>)}</div>{completed.length===total&&<div className="celebrate">🎉 <b>全部完成，开饭啦！</b></div>}</>}
function Inventory({items,remove,add}:{items:InventoryItem[];remove:(id:string)=>void;add:(item:InventoryItem)=>void}){const [adding,setAdding]=useState(false);const [name,setName]=useState("");const [amount,setAmount]=useState("");const submit=()=>{if(!name.trim())return;add({id:`custom-${Date.now()}`,name:name.trim(),amount:amount.trim()||"1 份",category:"其他",daysLeft:7,icon:"🥕"});setName("");setAmount("");setAdding(false)};return <><div className="inventory-summary top-space"><span><b>{items.length}</b> 种食材</span><span><b>{items.filter(i=>i.daysLeft<=3).length}</b> 项快到期</span><button onClick={()=>setAdding(!adding)}>{adding?"收起":"＋ 添加食材"}</button></div>{adding&&<div className="add-inventory"><input aria-label="食材名称" placeholder="食材名称，例如：胡萝卜" value={name} onChange={e=>setName(e.target.value)}/><input aria-label="食材数量" placeholder="数量，例如：3 根" value={amount} onChange={e=>setAmount(e.target.value)}/><button onClick={submit} disabled={!name.trim()}>加入库存</button></div>}<div className="inventory-grid">{items.map(item=><article className="inventory-card" key={item.id}><span>{item.icon}</span><div><h3>{item.name}</h3><p>{item.amount} · {item.category}</p><small className={item.daysLeft<=3?"urgent":""}>{item.daysLeft<=3?`⚠ ${item.daysLeft} 天内吃掉`:`保质期约 ${item.daysLeft} 天`}</small></div><button aria-label={`删除${item.name}`} onClick={()=>remove(item.id)}>×</button></article>)}</div><div className="inventory-tip"><span>💡</span><p><b>今晚优先建议</b>菠菜快到期了，下次推荐会优先出现菠菜相关菜品。</p></div></>}
function Stats({chosen}:{chosen:Dish[]}){const calories=chosen.reduce((s,d)=>s+d.calories,0);const protein=chosen.reduce((s,d)=>s+d.protein,0);const cost=chosen.reduce((s,d)=>s+d.cost,0);return <><div className="stat-grid top-space"><article><span>本月做饭</span><b>12 <small>顿</small></b><p>比上月多 3 顿</p></article><article><span>本月食材</span><b>$186</b><p>预算 $260 · 剩余 $74</p></article><article><span>减少浪费</span><b>7 <small>份</small></b><p>及时吃掉快到期食材</p></article></div><section className="budget-card"><div><p className="eyebrow">MONTHLY BUDGET</p><h2>八月厨房预算</h2><p>目前使用 72%，按这个节奏刚刚好。</p></div><div className="budget-ring"><span><b>72%</b><small>$186 / $260</small></span></div></section><section className="nutrition-card"><div><h2>今晚营养预估</h2><p>按两人份计算，仅供日常参考</p></div><div className="macro"><span><b>{calories||0}</b> kcal</span><span><b>{protein||0}g</b> 蛋白质</span><span><b>${cost.toFixed(0)}</b> 预计成本</span></div></section></>}
